### ISSUE TITLE
Select which subjects are being taken by students of a specific course

### ISSUE THREAD

**Issue by JPTIZ** [caravelahc/cagrex#10]
E.g. "Computer Science students have taken [...subjects...]", so it can be filtered as such:

- Select subjects of Computer Science students;
- Remove those from Computer Science curriculum;
- Now you know which outer subjects Computer Science students have interest.

Also show how many of these course's students are in these subjects.

**Comment by abarichello** [comment]
Fechando porque ninguém teve interesse em implementar e o CAGR está próximo do seu fim :(

**Comment by ranisalt** [comment]
> o CAGR está próximo do seu fim

O QUE
