### ISSUE TITLE
Select which campus

### ISSUE THREAD

**Issue by JPTIZ** [caravelahc/cagrex#8]
Currently every search considers only UFSC/FLO. It may stay as default, but adding an option to select which campus to search would be nice.

**Comment by ranisalt** [comment]
There could be a method to fetch all (campus, term) pairs. That would be a first request to get all available campuses, then one for each campus to get available terms, this last one might be pooled.

**Comment by abarichello** [comment]
https://github.com/caravelahc/cagrex/issues/10#issuecomment-813796221
